# Generated by Django 4.1.5 on 2023-01-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itens_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='is_finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado ou  em analise'),
        ),
    ]
