# Generated by Django 4.1.5 on 2023-01-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitacao_is_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observação'),
        ),
    ]
